export enum IActionType {
  CHANGE_TOP_BNNAER = 'recommend/CHANGE_TOP_BNNAER',
  CHANGE_HOT_RECOMMEND = 'recommend/CHANGE_HOT_RECOMMEND',
  CHANGE_NEW_ALBUM = 'recommend/CHANGE_NEW_ALBUM',
  CHANGE_UP_LIST = 'recommend/CHAGNE_UP_LIST',
  CHANGE_NEW_LIST = 'recommend/CHANGE_NEW_LIST',
  CHANGE_ORIGIN_LIST = 'recommend/CHANGE_ORIGIN_LIST',
  CHANGE_SETTLE_SONGER = 'recommend/CHANGE_SETTLE_SONGER'
}
