export enum IActionType {
  CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG',
  CHANGE_LYRICS = 'player/CHANGE_LYRICS',

  CHANGE_SIMI_PLAYLIST = 'player/CHANGE_SIMI_PLAYLIST',
  CHANGE_SIMI_SONGS = 'player/CHANGE_SIMI_SONGS',

  CHANGE_PLAY_LIST = 'player/CHANGE_PLAY_LIST',
  CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX',
  CHANGE_PLAY_SEQUENCE = 'player/CHANGE_PLAY_SEQUENCE',

  CHANGE_CURRENT_LYRIC_INDEX = 'player/CHANGE_CURRENT_LYRIC_INDEX'
}
