export enum IActionTypes {
  CHANGE_RADIO_CATEGORY = 'djradio/CHANGE_RADIO_CATEGORY',
  CHANGE_CURRENT_ID = 'djradio/CHANGE_CURRENT_ID',
  CHANGE_RECOMMENDS = 'djradio/CHANGE_RECOMMENDS',
  CHANGE_RADIOS = 'djradio/CHANGE_RADIOS'
}
